name: "Archive Issues and Pull Requests"

on:
  schedule:
    - cron: '0 0 * * 0,2,4'
  repository_dispatch:
    types: [archive]

jobs:
  build:
    name: "Archive Issues and Pull Requests"
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v2

    - name: "Update Archive"
      uses: martinthomson/i-d-template@v1
      with:
        make: archive
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: "Update GitHub Pages"
      uses: martinthomson/i-d-template@v1
      with:
        make: gh-archive
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: "Save Archive"
      uses: actions/upload-artifact@v2
      with:
        path: archive.json
