name: "Publish New Draft Version"

on:
  push:
    tags:
      - "draft-*"

jobs:
  build:
    name: "Publish New Draft Version"
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v2

    # See https://github.com/actions/checkout/issues/290
    - name: "Get Tag Annotations"
      run: git fetch -f origin ${{ github.ref }}:${{ github.ref }}

    - name: "Cache Setup"
      id: cache-setup
      run: |
        mkdir -p "$HOME"/.cache/xml2rfc
        echo "::set-output name=path::$HOME/.cache/xml2rfc"
        date -u "+::set-output name=date::%FT%T"

    - name: "Cache References"
      uses: actions/cache@v2
      with:
        path: ${{ steps.cache-setup.outputs.path }}
        key: refcache-${{ steps.date.outputs.date }}
        restore-keys: |
          refcache-${{ steps.date.outputs.date }}
          refcache-

    - name: "Upload to Datatracker"
      uses: martinthomson/i-d-template@v1
      with:
        make: upload
